name: Prod Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: |
          yarn install
      - name: Test Build
        run: |
          yarn build
        env:
          CI: false
          REACT_APP_GOOGLE_CLIENT_ID: ${{secrets.REACT_APP_GOOGLE_CLIENT_ID}}
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.PROD_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.REACT_DEPLOY_AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.REACT_DEPLOY_AWS_SECRET }}
          AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
          SOURCE_DIR: "build"
